rootProject.name = "Source"
include("API")
include("Extensions")
include("Extensions:Boosters")
include("Extensions:Counting")
include("Extensions:Cryptography")
include("Extensions:Documentation")
include("Extensions:Economy")
include("Extensions:Experience")
include("Extensions:Moderation")
include("Extensions:Music")
include("Extensions:Profiles")
include("Extensions:Starboard")
include("Extensions:Tags")
include("Extensions:Trivia")
include("Extensions:Latex")
include("Extensions:ReactionRoles")
